// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdcRMa_aFiDnEableuzIytV1pLt-Ldvk',
    appId: '1:2734661236:web:e530fc424cc0478926bb21',
    messagingSenderId: '2734661236',
    projectId: 'wewed-dc578',
    authDomain: 'wewed-dc578.firebaseapp.com',
    databaseURL: 'https://wewed-dc578-default-rtdb.firebaseio.com',
    storageBucket: 'wewed-dc578.appspot.com',
    measurementId: 'G-Q5JY0WB4LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwpXJLUKtOGCvnq8QId7aB5TEsL1xdPkw',
    appId: '1:2734661236:android:3effcde96163523726bb21',
    messagingSenderId: '2734661236',
    projectId: 'wewed-dc578',
    databaseURL: 'https://wewed-dc578-default-rtdb.firebaseio.com',
    storageBucket: 'wewed-dc578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjUGOWTYVFXRAb7oXhczkn3q1nKjhcBaY',
    appId: '1:2734661236:ios:498ce058184bc0b526bb21',
    messagingSenderId: '2734661236',
    projectId: 'wewed-dc578',
    databaseURL: 'https://wewed-dc578-default-rtdb.firebaseio.com',
    storageBucket: 'wewed-dc578.appspot.com',
    iosClientId: '2734661236-64g31rfbsj4kkmif6tfaoodkvh82knkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.weWed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjUGOWTYVFXRAb7oXhczkn3q1nKjhcBaY',
    appId: '1:2734661236:ios:987ca7a3900f191626bb21',
    messagingSenderId: '2734661236',
    projectId: 'wewed-dc578',
    databaseURL: 'https://wewed-dc578-default-rtdb.firebaseio.com',
    storageBucket: 'wewed-dc578.appspot.com',
    iosClientId: '2734661236-3fpcl0uon3nsti8q7vsvef0mgre5sogs.apps.googleusercontent.com',
    iosBundleId: 'com.example.weWed.RunnerTests',
  );
}
